### ISSUE TITLE
MenuCracker Doesn't work on OS X 10.11

### ISSUE THREAD

**Issue by JackoPlane** [perfaram/MenuCracker#2]
As title states, MenuCracker fails to load on OS X 10.11. Investigating further

**Comment by perfaram** [comment]
Holy shit, you're quick !

**Comment by perfaram** [comment]
I don't have access to the beta, so if you can find anything, just PR.

**Comment by zfdang** [comment]
anyone plan to fix this issue in osx 10.11?

**Comment by perfaram** [comment]
MenuCracker works by swizzling ObjC methods from its parent process, SystemUIServer. Swizzling cannot be done anymore with El Capitan *because of the very core feature of this OS, System Integrity Protection* (alias Rootless). This causes problems for many projects such as Flashlight (see nate-parrott/Flashlight#537, SIMBL (norio-nomura/EasySIMBL#26). Basically, every project which extended apps or system on OS X are screwed, because swizzling is now impossible.
